version: "3"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.2
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.toml:/traefik.toml"
      - "./config/acme.json:/acme.json"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
